# Generated by Django 5.0.4 on 2024-05-21 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_dashboard", "0001_create_book_table"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("""
                CREATE TABLE IF NOT EXISTS pinjam_buku (
                    user_id UUID,
                    book_id UUID,
                    start_date DATE,
                    end_date DATE
                )
                """),
            ],
            reverse_sql=[
                ("DROP TABLE IF EXISTS pinjam_buku")
            ]
        )
    ]
