# Generated by Django 5.0.4 on 2024-05-21 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_dashboard", "0002_pinjam_buku"),
    ]

    operations = []
